language: node_js
node_js:
  - '10'
branches:
  only:
  - master
before_script:
  - bash ./setenv.sh
jobs:
  include:
    - stage: "lint"
      script: npm run lint
    - stage: "test"
      script: npm run test
    - stage: "coverage"
      script: npm run coverage
